[package]
name = "bay"
version = "1.0.0"
authors = []

[addresses]
bay="0xf5c9fb83e9cd3209135ebf87050dddd0dcd5939f74aca6ebb02ea7acbeec3081"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dependencies.KADE_NETWORK]
git = "https://github.com/kade-net/network.git"
rev = "main"

[dev-dependencies]
